# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "ruby-2.1"
          - "ruby-2.2"
          - "ruby-2.3"
          - "ruby-2.4"
          - "ruby-2.5"
          - "ruby-2.6"
          - "ruby-2.7"
          - "ruby-3.0"
          - "ruby-3.1"
          - "ruby-3.2"
          - "ruby-3.3"
          - "jruby"
          - "truffleruby"

    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Run tests
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: |
            docker-compose.yml
            docker-compose-github.yml
            docker-compose-${{matrix.ruby}}.yml
          test-container: netsnmp
          test-command: /home/spec/support/specs.sh
        continue-on-error: ${{ matrix.ruby == 'jruby' || matrix.ruby == 'truffleruby' }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{matrix.ruby}}
          path: coverage/
